import Link from "next/link";
import FactsDesk from "./FactsDesk";

export const metadata = {
  title: "The Facts Desk — Miami Ledger",
  description:
    "Ask anything. Get the number, the source, and the context. A free fact-finding terminal from Miami Ledger.",
};

export default function FactsPage() {
  return (
    <div className="terminal-scanlines relative min-h-screen overflow-hidden bg-terminal-bg text-foreground">
      <div className="terminal-grid-bg absolute inset-0 opacity-50" />
      <div className="relative z-10 mx-auto max-w-[1400px] px-4 py-4 sm:px-6">
        <div className="flex flex-wrap items-center justify-between gap-3 border-b border-terminal-amber/20 pb-2 font-terminal text-[11px]">
          <div className="flex items-center gap-4">
            <Link
              href="/"
              className="rounded-sm border border-white/10 bg-white/5 px-2 py-1 uppercase tracking-widest text-foreground/70 hover:border-accent hover:text-accent"
            >
              ← Exit Facts
            </Link>
            <span className="font-editorial text-lg font-black uppercase tracking-tight text-foreground">
              Ledger<span className="text-terminal-amber">::Facts</span>
            </span>
            <span className="text-foreground/40">
              v0.1 · the bored-but-curious terminal
            </span>
          </div>
          <div className="flex items-center gap-4 text-foreground/40">
            <span className="text-terminal-green glow-green">● online</span>
            <Link
              href="/wire"
              className="rounded-sm border border-terminal-amber/40 bg-terminal-amber/10 px-2 py-1 uppercase tracking-widest text-terminal-amber hover:bg-terminal-amber/20"
            >
              → Wire
            </Link>
          </div>
        </div>

        <div className="my-6">
          <h1 className="font-editorial text-4xl font-bold tracking-tight text-foreground sm:text-5xl">
            The Facts Desk
          </h1>
          <p className="mt-2 max-w-2xl text-foreground/70">
            Ask anything. Get the number, the source, and the context. Miami,
            Florida, markets, world, weird — all of it. Free. No signup.
          </p>
        </div>

        <FactsDesk />

        <footer className="mt-10 border-t border-terminal-amber/20 pt-3 font-terminal text-[10px] uppercase tracking-widest text-foreground/40">
          Answers generated by DeepSeek, anchored to public sources where they
          exist. Numbers may lag — for live trading data hit the Wire; for
          stories hit the beats. The Desk is for chill curiosity.
        </footer>
      </div>
    </div>
  );
}
